cures = {
    "Apple___Apple_scab":"The most common medicine used to prevent apple scab is a fungicide. It is widely used fungicides for this purpose is Chlorothalonil. It's effective against various fungal diseases, including apple scab",
    "Apple___Black_rot":"Captan is a broad-spectrum fungicide that targets various fungal diseases, including apple black rot. It is available in different formulations such as wettable powder and liquid concentrate",
    "Apple___Cedar_apple_rust":"Thiophanate-methyl is a systemic fungicide that can be absorbed by plant tissues, providing longer-lasting protection against cedar apple rust and other fungal diseases",
    "Apple___healthy":"No preventive medicines required",
    "Blueberry___healthy":"No preventive medicines required",
    "Cherry___Powdery_mildew":"Triadimefon is a systemic fungicide that can be absorbed by plant tissues, providing longer-lasting protection against powdery mildew and other fungal diseases",
    "Cherry____healthy":"No preventive medicines required",
    "Corn___Cercospora_leaf_spot":"Azoxystrobin is a systemic fungicide from the strobilurin class that provides both preventative and curative control of cercospora leaf spot. It works by inhibiting fungal respiration",
    "Corn___Common_rust_":"Mancozeb is a broad-spectrum contact fungicide effective against common rust. It acts by disrupting fungal cell membranes and is often used in rotation with systemic fungicides to manage resistance",
    "Corn___Northern_Leaf_Blight":"Strobilurin fungicides also offer preventative and curative control of northern leaf blight. They work by disrupting fungal respiration and improving plant health.",
    "Corn___healthy":"No preventive medicines required",
    "Grape___Black_rot":"Boscalid is a systemic fungicide from the carboxamide group that provides preventive and curative control of grape black rot. It inhibits fungal respiration",
    "Grape___Esca":"There is no specific medicine or fungicide that can completely prevent grape esca.Pruning infected vines and removing diseased wood can help reduce the spread of esca within the vineyard.",
    "Grape___Leaf_blight)":"Recommended lime sulfur, sulfur or copper formulations to kill fungal spores that overwinter on the vine",
    "Grape___healthy":"No preventive medicines required",
    "Orange___Haunglongbing":"Huanglongbing (HLB), also known as citrus greening disease, is a devastating bacterial disease affecting citrus trees, including oranges.Proper fertilization and nutrient management can improve tree health and tolerance to HLB but cannot cure the disease.",
    "Peach___Bacterial_spot":"Peach bacterial spot caused by the bacterium Xanthomonas arboricola pv. pruni, can be managed using several strategies, including cultural practices and the application of certain copper-based bactericides",
    "Peach___healthy":"No preventive medicines required",
    "Pepper__bell___Bacterial_spot":"Streptomycin is an antibiotic bactericide that can be effective against bacterial spot in peppers. It works by interfering with bacterial protein synthesis.The use of streptomycin is limited due to concerns about antibiotic resistance and environmental impact. It is important to follow label instructions and use antibiotics responsibly",
    "Pepper__bell___healthy":"No preventive medicines required",
    "Potato___Early_blight":"Propiconazole is a systemic triazole fungicide effective against early blight and other fungal diseases. It is absorbed by plant tissues and provides long-lasting protection. Propiconazole is often used preventively and may be combined with other fungicides for improved disease control.",
    "Potato___Late_blight":"Mefenoxam is a systemic fungicide from the phenylamide group that provides preventive and curative control of late blight. It is absorbed by plant tissues and moves systemically within the plant, providing protection against the pathogen.",
    "Potato___healthy":"No preventive medicines required",
    "Raspberry___healthy":"No preventive medicines required",
    "Soybean___healthy":"No preventive medicines required",
    "Squash___Powdery_mildew":"",
    "Strawberry___Leaf_scorch":"Myclobutanil is another systemic triazole fungicide used to prevent and control strawberry leaf scorch. It is absorbed by plant tissues and translocated within the plant to provide protection against fungal pathogens.",
    "Strawberry___healthy":"No preventive medicines required",
    "Tomato___Bacterial_spot":"Proper plant spacing and pruning can improve air circulation within the canopy, reducing humidity and disease spread. Keep the area around tomato plants free of weeds, which can harbor disease pathogens and interfere with airflow.",
    "Tomato___Early_blight":"",
    "Tomato___Late_blight":"Apply mulch around tomato plants to help maintain soil moisture, reduce splashing of soil onto foliage, and minimize the spread of late blight spores.",
    "Tomato___Leaf_Mold":"Mefenoxam is a systemic fungicide from the phenylamide group that provides preventive and curative control of leaf mold. It is absorbed by plant tissues and moves systemically within the plant, providing protection against the pathogen.",
    "Tomato___Septoria_leaf_spot":"",
    "Tomato___Spider_mites Two-spotted_spider_mite":"Introduce predatory mites such as Phytoseiulus persimilis or Amblyseius californicus to feed on spider mites. These beneficial mites can help suppress spider mite populations.",
    "Tomato___Target_Spot":"Consider planting tomato varieties that are known to have some resistance or tolerance to target spot. Resistant varieties can help reduce disease severity and may require fewer fungicide applications",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus":"Use floating row covers or netting to physically exclude whiteflies from accessing tomato plant.Reflective mulch, such as silver or aluminum-colored mulch, can deter whiteflies by confusing them and reducing their attraction to tomato plants.",
    "Tomato___Tomato_mosaic_virus":"Proper sanitation is crucial to prevent the spread of ToMV. Disinfect gardening tools, such as pruners and stakes, before and after use, especially if they have come into contact with infected plants.",
    "Tomato___healthy":"No preventive medicines required"
}
